FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn --batch-mode --quiet dependency:go-offline

COPY src ./src
RUN mvn --batch-mode --quiet -DskipTests package

FROM eclipse-temurin:21-jre-jammy

RUN useradd --system --create-home spring

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

USER spring

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
