services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: linkpulse-backend
    restart: unless-stopped

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
      APP_BASE_URL: ${APP_BASE_URL}

    ports:
      - "8080:8080"